/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tst;
import Entity.Task;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ConnectException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.http.HttpResponse;
import org.apache.http.ParseException;
import org.apache.http.client.methods.HttpDelete;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPatch;
import org.apache.http.conn.HttpHostConnectException;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.util.EntityUtils;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;


/**
 *
 * @author Michal
 */
public class Client extends javax.swing.JFrame {

    CloseableHttpClient httpClient;
    List<Task> undoneTasks;
    String username="dezo";
    int page=4;
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        lblID1.setVisible(false);
        lblID2.setVisible(false);
        lblID3.setVisible(false);
        lblID4.setVisible(false);
        
        setFieldsVisibility();
        initHttpClient();
        initTasks();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        txtTitle1 = new javax.swing.JTextField();
        lblDescription1 = new javax.swing.JLabel();
        txtDesc1 = new javax.swing.JTextField();
        lblDate1 = new javax.swing.JLabel();
        txtDate1 = new javax.swing.JTextField();
        lblTime1 = new javax.swing.JLabel();
        txtTime1 = new javax.swing.JTextField();
        btnEdit1 = new javax.swing.JButton();
        bntDelete1 = new javax.swing.JButton();
        lblTitle2 = new javax.swing.JLabel();
        txtTitle2 = new javax.swing.JTextField();
        lblDescription2 = new javax.swing.JLabel();
        txtDesc2 = new javax.swing.JTextField();
        lblDate2 = new javax.swing.JLabel();
        txtDate2 = new javax.swing.JTextField();
        lblTime2 = new javax.swing.JLabel();
        txtTime2 = new javax.swing.JTextField();
        btnEdit2 = new javax.swing.JButton();
        bntDelete2 = new javax.swing.JButton();
        lblTitle3 = new javax.swing.JLabel();
        txtTitle3 = new javax.swing.JTextField();
        lblDescription3 = new javax.swing.JLabel();
        txtDesc3 = new javax.swing.JTextField();
        lblDate3 = new javax.swing.JLabel();
        txtDate3 = new javax.swing.JTextField();
        lblTime3 = new javax.swing.JLabel();
        txtTime3 = new javax.swing.JTextField();
        btnEdit3 = new javax.swing.JButton();
        bntDelete3 = new javax.swing.JButton();
        lblTitle4 = new javax.swing.JLabel();
        txtTitle4 = new javax.swing.JTextField();
        lblDescription4 = new javax.swing.JLabel();
        txtDesc4 = new javax.swing.JTextField();
        lblDate4 = new javax.swing.JLabel();
        txtDate4 = new javax.swing.JTextField();
        lblTime4 = new javax.swing.JLabel();
        txtTime4 = new javax.swing.JTextField();
        btnEdit4 = new javax.swing.JButton();
        bntDelete4 = new javax.swing.JButton();
        btnSetDone1 = new javax.swing.JButton();
        btnSetDone2 = new javax.swing.JButton();
        btnSetDone3 = new javax.swing.JButton();
        btnSetDone4 = new javax.swing.JButton();
        lblID1 = new javax.swing.JLabel();
        lblID2 = new javax.swing.JLabel();
        lblID3 = new javax.swing.JLabel();
        lblID4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNewTask = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblCloseTask = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle1.setText("Title");

        txtTitle1.setEditable(false);

        lblDescription1.setText("Desciption");

        txtDesc1.setEditable(false);

        lblDate1.setText("Date");

        txtDate1.setEditable(false);

        lblTime1.setText("Time");

        txtTime1.setEditable(false);

        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        bntDelete1.setText("Delete");
        bntDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDelete1ActionPerformed(evt);
            }
        });

        lblTitle2.setText("Title");

        txtTitle2.setEditable(false);

        lblDescription2.setText("Desciption");

        txtDesc2.setEditable(false);

        lblDate2.setText("Date");

        txtDate2.setEditable(false);

        lblTime2.setText("Time");

        txtTime2.setEditable(false);

        btnEdit2.setText("Edit");
        btnEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit2ActionPerformed(evt);
            }
        });

        bntDelete2.setText("Delete");
        bntDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDelete2ActionPerformed(evt);
            }
        });

        lblTitle3.setText("Title");

        txtTitle3.setEditable(false);

        lblDescription3.setText("Desciption");

        txtDesc3.setEditable(false);
        txtDesc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesc3ActionPerformed(evt);
            }
        });

        lblDate3.setText("Date");

        txtDate3.setEditable(false);
        txtDate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate3ActionPerformed(evt);
            }
        });

        lblTime3.setText("Time");

        txtTime3.setEditable(false);

        btnEdit3.setText("Edit");
        btnEdit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit3ActionPerformed(evt);
            }
        });

        bntDelete3.setText("Delete");
        bntDelete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDelete3ActionPerformed(evt);
            }
        });

        lblTitle4.setText("Title");

        txtTitle4.setEditable(false);
        txtTitle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitle4ActionPerformed(evt);
            }
        });

        lblDescription4.setText("Desciption");

        txtDesc4.setEditable(false);

        lblDate4.setText("Date");

        txtDate4.setEditable(false);

        lblTime4.setText("Time");

        txtTime4.setEditable(false);

        btnEdit4.setText("Edit");
        btnEdit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit4ActionPerformed(evt);
            }
        });

        bntDelete4.setText("Delete");
        bntDelete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDelete4ActionPerformed(evt);
            }
        });

        btnSetDone1.setText("Set Done");
        btnSetDone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDone1ActionPerformed(evt);
            }
        });

        btnSetDone2.setText("Set Done");
        btnSetDone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDone2ActionPerformed(evt);
            }
        });

        btnSetDone3.setText("Set Done");
        btnSetDone3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDone3ActionPerformed(evt);
            }
        });

        btnSetDone4.setText("Set Done");
        btnSetDone4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDone4ActionPerformed(evt);
            }
        });

        btnPrev.setText("Previous");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnPrev)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnNext)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblID1)
                            .addComponent(lblID2)
                            .addComponent(lblID3)
                            .addComponent(lblID4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle2)
                            .addComponent(lblTitle3)
                            .addComponent(lblTitle4))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblDescription4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesc4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblDescription3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesc3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescription1)
                                    .addComponent(lblDescription2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblDate4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDate4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblDate3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblDate2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblDate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblTime4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(txtTime4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblTime3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblTime1)
                                .addGap(18, 18, 18)
                                .addComponent(txtTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblTime2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(bntDelete1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSetDone1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(bntDelete2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSetDone2))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(bntDelete4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSetDone4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(bntDelete3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSetDone3)))))
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1)
                    .addComponent(txtTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription1)
                    .addComponent(txtDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate1)
                    .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime1)
                    .addComponent(txtTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit1)
                    .addComponent(bntDelete1)
                    .addComponent(btnSetDone1)
                    .addComponent(lblID1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitle2)
                        .addComponent(txtTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescription2)
                        .addComponent(lblDate2)
                        .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTime2)
                        .addComponent(txtTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit2)
                        .addComponent(bntDelete2)
                        .addComponent(btnSetDone2)
                        .addComponent(lblID2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle3)
                    .addComponent(txtTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription3)
                    .addComponent(txtDesc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTime3)
                    .addComponent(txtTime3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit3)
                    .addComponent(bntDelete3)
                    .addComponent(btnSetDone3)
                    .addComponent(lblID3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle4)
                    .addComponent(txtTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription4)
                    .addComponent(txtDesc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate4)
                    .addComponent(txtDate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime4)
                    .addComponent(txtTime4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit4)
                    .addComponent(bntDelete4)
                    .addComponent(btnSetDone4)
                    .addComponent(lblID4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        jTabbedPane4.addTab("Tasks", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("History", jPanel2);

        btnNewTask.setText("New task");
        btnNewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTaskActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel1.setText("Close Task is");

        lblCloseTask.setText("jLabel2");

        lblCount.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCount)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCloseTask, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewTask)
                    .addComponent(jLabel1)
                    .addComponent(lblCloseTask)
                    .addComponent(btnLogOut))
                .addGap(8, 8, 8)
                .addComponent(lblCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTaskActionPerformed
        
        NewTask newTask= new NewTask(this,username);
        //newTask.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                newTask.setVisible(true);
            }
        });
    }//GEN-LAST:event_btnNewTaskActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        username=null;
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        page=page+4;
        setFieldsVisibility();
        printTasks(undoneTasks, page);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        page=page-4;
        setFieldsVisibility();
        printTasks(undoneTasks, page);
    }//GEN-LAST:event_btnPrevActionPerformed

    private void bntDelete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDelete4ActionPerformed
        try {
            deleteTaskByID("http://localhost:8080/"+username+"/tasks/" + lblID4.getText());
            refreshTasks();
            message("","Task with ID " + lblID4.getText() +" was deleted");           
        } catch (IOException ex) {
            message("Error","Cloud not conncect to server");
        }
    }//GEN-LAST:event_bntDelete4ActionPerformed

    private void btnEdit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit4ActionPerformed
        Task tmp=getTaskByID(lblID4.getText());
        if(tmp!=null)
        editTask(tmp);
    }//GEN-LAST:event_btnEdit4ActionPerformed

    private void txtTitle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitle4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitle4ActionPerformed

    private void bntDelete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDelete3ActionPerformed
        try {
            deleteTaskByID("http://localhost:8080/"+username+"/tasks/" + lblID3.getText());
            refreshTasks();
            message("","Task with ID " + lblID3.getText() +" was deleted");           
        } catch (IOException ex) {
            message("Error","Cloud not conncect to server");
        }
    }//GEN-LAST:event_bntDelete3ActionPerformed

    private void btnEdit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit3ActionPerformed
        Task tmp=getTaskByID(lblID3.getText());
        if(tmp!=null)
        editTask(tmp);
    }//GEN-LAST:event_btnEdit3ActionPerformed

    private void txtDate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate3ActionPerformed

    private void txtDesc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesc3ActionPerformed

    private void bntDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDelete2ActionPerformed
        try {
            deleteTaskByID("http://localhost:8080/"+username+"/tasks/" + lblID2.getText());
            message("","Task with ID = " + lblID2.getText() +" was deleted");
            
        } catch (IOException ex) {
            message("Error","Cloud not conncect to server");
        }
    }//GEN-LAST:event_bntDelete2ActionPerformed

    private void btnEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit2ActionPerformed
        Task tmp=getTaskByID(lblID2.getText());
        if(tmp!=null)
        editTask(tmp);
    }//GEN-LAST:event_btnEdit2ActionPerformed

    private void bntDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDelete1ActionPerformed
        try {
            deleteTaskByID("http://localhost:8080/"+username+"/tasks/" + lblID1.getText());
            refreshTasks();
            message("","Task with ID " + lblID1.getText() +" was deleted");           
        } catch (IOException ex) {
            message("Error","Cloud not conncect to server");
        }
    }//GEN-LAST:event_bntDelete1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed

        Task tmp=getTaskByID(lblID1.getText());
        if(tmp!=null)
        editTask(tmp);
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnSetDone4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDone4ActionPerformed
        try {
            int code= saveTask("http://localhost:8080/"+username+"/tasks/"+ lblID4.getText());
            if(code == 200){          
                message("","Task was set done");
            }
            else{
                message("Error","Task was not set done");
            }
        } catch (IOException ex) {
           message("Error","Cloud not conncect to server");
        } 
    }//GEN-LAST:event_btnSetDone4ActionPerformed

    private void btnSetDone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDone1ActionPerformed
        try {
            int code= saveTask("http://localhost:8080/"+username+"/tasks/"+ lblID1.getText());
            if(code == 200){          
                message("","Task was set done");
            }
            else{
                message("Error","Task was not set done");
            }
        } catch (IOException ex) {
           message("Error","Cloud not conncect to server");
        } 
    }//GEN-LAST:event_btnSetDone1ActionPerformed

    private void btnSetDone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDone2ActionPerformed
        try {
            int code= saveTask("http://localhost:8080/"+username+"/tasks/"+ lblID2.getText());
            if(code == 200){          
                message("","Task was set done");
            }
            else{
                message("Error","Task was not set done");
            }
        } catch (IOException ex) {
           message("Error","Cloud not conncect to server");
        } 
    }//GEN-LAST:event_btnSetDone2ActionPerformed

    private void btnSetDone3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDone3ActionPerformed
        try {
            int code= saveTask("http://localhost:8080/"+username+"/tasks/"+ lblID3.getText());
            if(code == 200){          
                message("","Task was set done");
            }
            else{
                message("Error","Task was not set done");
            }
        } catch (IOException ex) {
           message("Error","Cloud not conncect to server");
        } 
    }//GEN-LAST:event_btnSetDone3ActionPerformed

   private void editTask(Task task){
      EditTask editTaskdialog= new EditTask(task,this,username);
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    editTaskdialog.setVisible(true);
            }
        });
   }
   
   private int saveTask(String url) throws IOException{      
            int code=0;       
            HttpPatch request = new HttpPatch(url);
            request.setHeader("content-type", "application/json");     
            StringEntity params=new StringEntity("{\"done\":true}");
            request.setEntity(params);
            HttpResponse response = httpClient.execute(request);
            System.out.println("Response Code : "+ response.getStatusLine().getStatusCode());
            code=Integer.valueOf(response.getStatusLine().getStatusCode());      
            refreshTasks();
            return code;
    }
   
   private void initHttpClient(){
           httpClient = HttpClientBuilder.create().build();   
   }
   
   
  private void setFieldsVisibility(){
        
        lblTitle1.setVisible(false);
        lblDescription1.setVisible(false);
        lblDate1.setVisible(false);
        lblTime1.setVisible(false);
        btnEdit1.setVisible(false);
        btnSetDone1.setVisible(false);
        bntDelete1.setVisible(false);
      
        txtTitle1.setVisible(false);
        txtDesc1.setVisible(false);
        txtDesc1.setVisible(false);
        txtDate1.setVisible(false);
        txtTime1.setVisible(false);
        
        lblTitle2.setVisible(false);
        lblDescription2.setVisible(false);
        lblDate2.setVisible(false);
        lblTime2.setVisible(false);
        btnEdit2.setVisible(false);
        btnSetDone2.setVisible(false);
        bntDelete2.setVisible(false);
        
        txtTitle2.setVisible(false);
        txtDesc2.setVisible(false);
        txtDesc2.setVisible(false);
        txtDate2.setVisible(false);
        txtTime2.setVisible(false);
        
        lblTitle3.setVisible(false);
        lblDescription3.setVisible(false);
        lblDate3.setVisible(false);
        lblTime3.setVisible(false);
        btnEdit3.setVisible(false);
        btnSetDone3.setVisible(false);
        bntDelete3.setVisible(false);
        
        txtTitle3.setVisible(false);
        txtDesc3.setVisible(false);
        txtDesc3.setVisible(false);
        txtDate3.setVisible(false);
        txtTime3.setVisible(false);
        
        lblTitle4.setVisible(false);
        lblDescription4.setVisible(false);
        lblDate4.setVisible(false);
        lblTime4.setVisible(false);
        btnEdit4.setVisible(false);
        btnSetDone4.setVisible(false);
        bntDelete4.setVisible(false);
        
        txtTitle4.setVisible(false);
        txtDesc4.setVisible(false);
        txtDesc4.setVisible(false);
        txtDate4.setVisible(false);
        txtTime4.setVisible(false);
   
   }
   
    
    private void initTasks(){
       
        try {
            undoneTasks = getAllUndoneTasks("http://localhost:8080/"+username+"/tasks");
            printTasks(undoneTasks,page);
        } catch (IOException ex) {
            message("Error","Cloud not conncect to server");
        }  
    }
    
    public void printTasks(List<Task> tasks,int page){
        
        int index;   
        for(index=page-4;index<page;index++){
           try{
            Task task= tasks.get(index);
               
            switch(index%4){
                case 0:
                        lblID1.setText(String.valueOf(task.getId()));
                        lblTitle1.setVisible(true);
                        lblDescription1.setVisible(true);
                        lblDate1.setVisible(true);
                        lblTime1.setVisible(true);
                        txtTitle1.setVisible(true);
                        txtTitle1.setText(task.getName());
                        txtDesc1.setVisible(true);
                        txtDesc1.setText(task.getDescription());                                            
                        txtDate1.setText(formatDate(task.getTaskDate()));
                        txtDate1.setVisible(true);                                   
                        txtTime1.setText(formatTime(task.getTaskTime()));
                        txtTime1.setVisible(true);
                        
                        btnEdit1.setVisible(true);
                        bntDelete1.setVisible(true);
                        btnSetDone1.setVisible(true);
                        break;
                case 1: 
                        lblID2.setText(String.valueOf(task.getId()));
                        lblTitle2.setVisible(true);
                        lblDescription2.setVisible(true);
                        lblDate2.setVisible(true);
                        lblTime2.setVisible(true);
                        txtTitle2.setVisible(true);
                        txtTitle2.setText(task.getName());
                        txtDesc2.setVisible(true);
                        txtDesc2.setText(task.getDescription());                       
                        txtDate2.setText(formatDate(task.getTaskDate()));
                        txtDate2.setVisible(true);
                        txtTime2.setText(formatTime(task.getTaskTime()));
                        txtTime2.setVisible(true);
                        
                        btnEdit2.setVisible(true);
                        bntDelete2.setVisible(true);
                        btnSetDone2.setVisible(true);
                        break;
                case 2:
                        lblID3.setText(String.valueOf(task.getId()));
                        lblTitle3.setVisible(true);
                        lblDescription3.setVisible(true);
                        lblDate3.setVisible(true);
                        lblTime3.setVisible(true);
                        txtTitle3.setVisible(true);
                        txtTitle3.setText(task.getName());
                        txtDesc3.setVisible(true);
                        txtDesc3.setText(task.getDescription());                      
                        txtDate3.setText(formatDate(task.getTaskDate()));
                        txtDate3.setVisible(true);
                        txtTime3.setText(formatTime(task.getTaskTime()));
                        txtTime3.setVisible(true);
                        
                        btnEdit3.setVisible(true);
                        bntDelete3.setVisible(true);
                        btnSetDone3.setVisible(true);
                        break;
                case 3:
                        lblTitle4.setVisible(true);
                        lblDescription4.setVisible(true);
                        lblDate4.setVisible(true);
                        lblTime4.setVisible(true);
                        lblID4.setText(String.valueOf(task.getId()));
                        txtTitle4.setVisible(true);
                        txtTitle4.setText(task.getName());
                        txtDesc4.setVisible(true);
                        txtDesc4.setText(task.getDescription());                    
                        txtDate4.setText(formatDate(task.getTaskDate()));
                        txtDate4.setVisible(true);
                        txtTime4.setText(formatTime(task.getTaskTime()));
                        txtTime4.setVisible(true);
                        
                        btnEdit4.setVisible(true);
                        bntDelete4.setVisible(true);
                        btnSetDone4.setVisible(true);
                        break;
            }  
           }catch(IndexOutOfBoundsException e){
               break;
           }
        }
        
        if(page+4>tasks.size()+4){
            btnNext.setVisible(false);
            btnPrev.setVisible(true);
        }
        if(page-4<=0){
             btnPrev.setVisible(false);
             btnNext.setVisible(true);
        }
       
 
      
    }
    
    public void refreshTasks(){
       
        try {
            List<Task> tasks = getAllUndoneTasks("http://localhost:8080/"+username+"/tasks");
            setFieldsVisibility();
            printTasks(tasks,page);
        } catch (IOException ex) {
            message("Error","Cloud not conncect to server");
        }
    }
    
    private int deleteTaskByID(String url) throws IOException{
        
            int code=0;       
            HttpDelete request = new HttpDelete(url);
            HttpResponse response = httpClient.execute(request);
            System.out.println("Response Code : "+ response.getStatusLine().getStatusCode());
            code=Integer.valueOf(response.getStatusLine().getStatusCode());
            refreshTasks();           
            return code;
    }
    
    
    
 private List<Task> getAllUndoneTasks(String url) throws IOException {

     List<Task> tasksUndone= new ArrayList<>();
     
            HttpGet request = new HttpGet(url);
            HttpResponse response = httpClient.execute(request);
            System.out.println("Response Code : "+ response.getStatusLine().getStatusCode());
            
             String json = EntityUtils.toString(response.getEntity(), "UTF-8");
             undoneTasks= new ArrayList<>();
             try {
              
                JSONParser parser = new JSONParser();
                Object resultObject = parser.parse(json);

                if (resultObject instanceof JSONArray) {
                    JSONArray array=(JSONArray)resultObject;
                    for (Object object : array) {
                        JSONObject obj =(JSONObject)object;
                        
                        long id = Long.valueOf(obj.get("id").toString());
                        String name = obj.get("name").toString();
                        String description = obj.get("description").toString();
                        boolean done= Boolean.valueOf(obj.get("done").toString());
                        
                        String strTime=obj.get("taskTime").toString();
                        DateFormat df = new SimpleDateFormat("HH:mm:ss");
                        Date taskTime =  df.parse(strTime); 
                        
                        String strDate=obj.get("taskDate").toString(); 
                         df = new SimpleDateFormat("yyyy-MM-dd");
                        Date taskDate =  df.parse(strDate);  
                        
                        undoneTasks.add(new Task(id,name,description,done,taskTime,taskDate));
                        
                    }

                }else if (resultObject instanceof JSONObject) {
                    JSONObject obj =(JSONObject)resultObject;
                    long id = Long.valueOf(obj.get("id").toString());
                        String name = obj.get("name").toString();
                        String description = obj.get("description").toString();
                        boolean done= Boolean.valueOf(obj.get("done").toString());
                        
                        String strTime=obj.get("taskTime").toString();
                        DateFormat df = new SimpleDateFormat("HH:mm:ss");
                        Date taskTime =  df.parse(strTime); 
                        
                        String strDate=obj.get("taskDate").toString(); 
                         df = new SimpleDateFormat("yyyy-MM-dd");
                        Date taskDate =  df.parse(strDate);  
                        
                        undoneTasks.add(new Task(id,name,description,done,taskTime,taskDate));
                }

            }catch(Exception e){
                 System.out.println("error");
            }
      
     for(Task task: undoneTasks){
         if(!task.isDone()){
         tasksUndone.add(task);
         }
     }
     
     return tasksUndone;
    }
    

private Task getTaskByID(String strID ){
   
    long id=Integer.valueOf(strID);
    
    for (Task task: undoneTasks){
        if(id == task.getId()){
             return task;
        }
    }
    return null;
}

private void message(String title, String message){
    
    MessageDialog msg= new MessageDialog(title,message);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                msg.setVisible(true);              
            }
            });
}

private String formatDate(Date date){
    DateFormat df = new SimpleDateFormat("dd.MM.yyyy"); 
    return df.format(date);
}

private String formatTime(Date time){
    DateFormat df = new SimpleDateFormat("HH:mm"); 
    return df.format(time);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDelete1;
    private javax.swing.JButton bntDelete2;
    private javax.swing.JButton bntDelete3;
    private javax.swing.JButton bntDelete4;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnEdit2;
    private javax.swing.JButton btnEdit3;
    private javax.swing.JButton btnEdit4;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNewTask;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSetDone1;
    private javax.swing.JButton btnSetDone2;
    private javax.swing.JButton btnSetDone3;
    private javax.swing.JButton btnSetDone4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel lblCloseTask;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblDate3;
    private javax.swing.JLabel lblDate4;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblDescription2;
    private javax.swing.JLabel lblDescription3;
    private javax.swing.JLabel lblDescription4;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblID3;
    private javax.swing.JLabel lblID4;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JLabel lblTime3;
    private javax.swing.JLabel lblTime4;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JTextField txtDate1;
    private javax.swing.JTextField txtDate2;
    private javax.swing.JTextField txtDate3;
    private javax.swing.JTextField txtDate4;
    private javax.swing.JTextField txtDesc1;
    private javax.swing.JTextField txtDesc2;
    private javax.swing.JTextField txtDesc3;
    private javax.swing.JTextField txtDesc4;
    private javax.swing.JTextField txtTime1;
    private javax.swing.JTextField txtTime2;
    private javax.swing.JTextField txtTime3;
    private javax.swing.JTextField txtTime4;
    private javax.swing.JTextField txtTitle1;
    private javax.swing.JTextField txtTitle2;
    private javax.swing.JTextField txtTitle3;
    private javax.swing.JTextField txtTitle4;
    // End of variables declaration//GEN-END:variables
}
